swagger:
  title: '摸鱼低代码平台'
  enabled: true
  description : 摸鱼框架接口文档
  license : Powered By mfish
  licenseUrl : https://github.com/mfish-qf/mfish-nocode/blob/main/LICENSE
  version : 版本号:V1.3.0
  termsOfServiceUrl : http://www.mfish.com.cn
  contact:
    name: mfish
    email: qiufeng9862@qq.com
    url: http://www.mfish.com.cn
  needAuth : true
springdoc:
  api-docs:
    #生产设置false
    enabled: true
  swagger-ui:
    #生产设置false
    enabled: true
    path: /index.html
    tags-sorter: alpha
    operations-sorter: alpha
    default-models-expand-depth: -1
    docExpansion: none
  group-configs:
    - group: mfish-nocode
      paths-to-match: /**
  default-flat-param-object: true