gateway:
  routes:
    - path: /oauth2
      packageName: cn.com.mfish.oauth
    - path: /scheduler
      packageName: cn.com.mfish.scheduler
    - path: /storage
      packageName: cn.com.mfish.storage
    - path: /sys
      packageName: cn.com.mfish.sys
    - path: /demo
      packageName: cn.com.mfish.demo
    - path: /nocode
      packageName: cn.com.mfish.nocode