# 可匿名访问的路径（不校验白名单）
security:
  ignore:
    whites:
      - "/oauth2/user/revoke"
      - "/oauth2/authorize"
      - "/oauth2/accessToken"
      - "/oauth2/sendMsg"
      - "/oauth2/qrCodeLogin/**"
      - "/oauth2/wx/bind/**"
      - "/oauth2/static/**"
      - "/oauth2/gitee/**"
      - "/oauth2/github/**"
      - "/captcha"
      - "/storage/file/*.*"
      - "/css/**"
      - "/img/**"
      - "/js/**"
      - "/fonts/**"
      - "/wx/**"
      - "/swagger-ui/**"
      - "/swagger-resources/**"
      - "/v3/api-docs/**"
      - "/404"
