spring:
  ai:
    openai:
#      api-key: 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
#      base-url: https://openrouter.ai/api
      api-key: AIzaSyAJacktgJI4BAErMG4l3LQ7kBDl9lNBRG0
      base-url: https://ai.mfish.qzz.io/v1beta/openai/
      chat:
        # 用Gemini时这个路径不对，需要修改
        completions-path: /chat/completions
        options:
          max-tokens: 1000
          temperature: 0.7
          model: gemini-2.5-flash-lite
#          model: deepseek/deepseek-r1-0528:free
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:8b