code:
  template:
    keys:
      - src/main/java/${packageName}/controller/${entityName}Controller.java.ftl
      - src/main/java/${packageName}/entity/${entityName}.java.ftl
      - src/main/java/${packageName}/mapper/${entityName}Mapper.java.ftl
      - src/main/java/${packageName}/mapper/xml/${entityName}Mapper.xml.ftl
      - src/main/java/${packageName}/req/Req${entityName}.java.ftl
      - src/main/java/${packageName}/service/${entityName}Service.java.ftl
      - src/main/java/${packageName}/service/impl/${entityName}ServiceImpl.java.ftl
      - mfish-nocode-view/src/views/${apiPrefix}/${entityName#kebab-case}/${entityName#uncap_first}.data.ts.ftl
      - mfish-nocode-view/src/views/${apiPrefix}/${entityName#kebab-case}/${entityName}Modal.vue.ftl
      - mfish-nocode-view/src/views/${apiPrefix}/${entityName#kebab-case}/${entityName}ViewModal.vue.ftl
      - mfish-nocode-view/src/views/${apiPrefix}/${entityName#kebab-case}/index.vue.ftl
      - mfish-nocode-view/src/api/${apiPrefix}/model/${entityName}Model.ts.ftl
      - mfish-nocode-view/src/api/${apiPrefix}/${entityName}.ts.ftl
    path: template
  savePath:
    #前端地址
    front: E:/javacode/mfish-nocode-pro
    #后端地址（需要指定到具体模块路径）
    back: E:/javacode/mfish-nocode-pro/mf-business/mf-demo